### ISSUE TITLE
SELECT 1

### ISSUE THREAD

**Issue by smaili** [hiddentao/squel#139]
Hey there,

Trying to generate the super simple `SELECT 1` query for a keep alive function I have, but unfortunately when I run the following:

```
squel.select()
    .field( '1' )
    .toString()
``` 

I get the message `from() needs to be called`.

I know something like this is overkill for squel, but I would like to keep my code consistent for all query building, so I'm just wondering if this is something that is currently possible and I'm not doing it correctly, or if this is a use case that squel hasn't yet been designed to handle?

**Comment by hiddentao** [comment]
Squel was designed to assume access from a table. We might be able to remove that `from()` call check. Will look into it.

**Comment by HarryPehkonen** [comment]
I realize `SELECT NOW() AS "theTime"` is very simple to leave as a string, but it would be a "nice to have" feature to skip the from()-check.

**Comment by msmaili** [comment]
I think having that check there can actually be helpful for developers that may accidentally forget to have included a table in their query, but I think having the flexibility of making it an actual requirement can also be very useful for the occasional times where it actually isn't needed.

My proposal to solve this is rather than completely make the table optional, instead have it check if the value is explicitly set to `false`, this way it's cleaner for readability from the developer's point of view, and it still allows squel to keep its table checker in place for making sure the developer didn't accidentally forget to provide a table.

```
// Generates "SELECT 1"
squel.select()
    .field( '1' )
    .from( false )
    .toString()

// Generates Error
squel.select()
    .field( '1' )
    .toString()
```

**Comment by zachguo** [comment]
:+1: It's also needed when `SELECT LAST_INSERT_ID();`.

**Comment by idonman** [comment]
And SELECT currval() or nextval()

**Comment by mavrick** [comment]
Also would love to see support for ```SQL_CALC_FOUND_ROWS``` or similar ```SELECT FOUND_ROWS();```

**Comment by hiddentao** [comment]
Fixed in 4.2.0:

```js
squel.select().function('1')

/*  SELECT 1 */

squel.select().function('MAX(?, ?)', 45, 87)

/*  SELECT MAX(45, 87) */
```

**Comment by smaili** [comment]
Semantically, I'm not sure if `1` would be considered a function, but nonetheless thank you @hiddentao!!!

**Comment by hiddentao** [comment]
Yeah I know, just wanted to keep the API simple yet expressive enough :)
