### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by RoRoche** [hiddentao/squel#173]
Is it possible to provide a ".d.ts" file in order to use squel in TypeScript project?

**Comment by hiddentao** [comment]
I'm not familiar with Typescript myself - what benefit would this provide?

**Comment by bchociej** [comment]
AFAIK this would essentially be a sort of "header file" that TypeScript uses to expose this library's interface to TypeScript projects. Unless we have somebody willing to maintain such a thing it'd be a bit of a pain, but certainly useful to certain folks.

**Comment by hiddentao** [comment]
It sounds like the sort of thing we'd want to auto-generate from our API if possible. One of the downsides to Squel's current architecture is that it's difficult to automatically derive the public API. For the documentation pages we have to manually add it in - ironically the documentation pages would work as a source for auto-generation of said header files.

**Comment by DmitryEfimenko** [comment]
+1
Anyone looked into this further?
Maybe someone has started composing d.ts file? If so, please share!

**Comment by mavrick** [comment]
+1

**Comment by DmitryEfimenko** [comment]
@hiddentao in case the question "what benefit would this provide?" still stands, here is a good [introduction to TypeScript talk](https://youtu.be/_TDUV9R09PM) from AngularConnect.

**Comment by xiewei-wayne** [comment]
typescript + angular 2.0, becomes famous.

**Comment by demurgos** [comment]
> It sounds like the sort of thing we'd want to auto-generate from our API if possible. One of the downsides to Squel's current architecture is that it's difficult to automatically derive the public API. For the documentation pages we have to manually add it in - ironically the documentation pages would work as a source for auto-generation of said header files.

Regarding the issues to maintain the documentation, I feel that it still would be better to have the documentation generated from the code and note the other way around (it's just more reliable).
I submitted a PR (#322) to with full types and doc comments for Squel. You could take a look at Typedoc and use these type definitions to generate the documentation. The main advantages is that it is a somewhat "formal" way to define your API and would keep both the type definitions and human-readable documentation in sync. It would also allow you to elegantly solve your problems with documentation generation due to the block architecture: the types I sent define the query builders as sums of partial interfaces provided by each involved block.
